#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get install -y nginx

sudo touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html >/dev/null
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

sudo sed -i '/listen 80 default_server/a\
        location /redirect_me {\
                return 301 http://google.com/;\
        }\
        error_page 404 /404.html;\
        location /404 {\
                root /var/www/html;\
                internal;\
        }' /etc/nginx/sites-available/default
sudo service nginx restart
